import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Readinggate Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
