import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
  //   const searchParams = request.nextUrl.searchParams

  const student = {
    StudentId: '000172C2019014871',
    Name: '박태민',
    LoginId: 'sbpst',
    RevisionCount: '10',
    StudentEmail: 'sbpst2@naver.com',
    ParentCellPhone: '0106338008',
    ParentEmail: 'sbpst2@hanmail.net',
    ParentName: '박태민',
    PhotoFilename2:
      'http://fservice6.readinggate.com/UPLOADFILE/MyPage/000172/46832937c2cd480a57ecb6d68ef0d95d.jpg',
    AttendSmsYn: 'N',
    WeeklySmsYn: 'Y',
    MonthlySmsYn: 'Y',
    StudySetupYn: 'N',
    BrCount: '656',
    RgPoint: '3227.7599999999998',
    StudyEndDate: '9999-12-30',
    StudyEndDay: '9999',
    LevelTestYn: 'N',
    LastLevelTest: '3B',
    LastLevelUp: 'KA',
    ClassId: '000172C2019000033',
    ClassName: '박태민반',
    StudyAbleYn: 'Y',
    StudyAbleYnMsg: '',
    PushYn: 'N',
    AdjustStatus: 'R',
    AdjustCnt: '0',
    StartScreen: 'Home',
    ViewStep3Hint: 'Y',
    ViewStep2Skip: 'Y',
    EBKListenRepeat: 'N',
    EB1ListenRepeat: 'N',
    SmsStudyReportYn: 'Y',
    OverseasYn: 'N',
    StudyReadingUnitId: '097906',
    CntThisYear: '0',
    SuspendStart: '',
    SuspendEnd: '',
    AddAbleStudyYn: 'Y',
    BookWizardYn: 'Y',
    StudyLevelName: '4B',
    AttendYn: 'Y',
    CountStudyYn: 'Y',
    ExperienceClass: 'N',
    NeedGroupClassYn: 'N',
    ChangeClassDateYn: 'N',
    CancelButtonYn: 'N',
    donationBookCnt: '6',
    LibraryFindSortName: 'RegistDate',
    LibraryStatusName: 'StatusCompleted',
    LibraryGenreName: 'GenreAll',
    LibraryPBFindSortName: 'ReadCount',
    LibraryPBStatusName: 'StatusAll',
    LibraryPBGenreName: 'GenreAll',
    LibraryKinderCourseName: 'CourseAll',
    RegistDate: '2019-04-22',
    ViewRecommendBooksYn: 'Y',
    StudyEBUseYn: 'Y',
    StudyPBUseYn: 'Y',
    UseDodoAbcYn: 'Y',
    ViewLevelUpYn: 'Y',
    ViewVocaYn: 'Y',
    StudentWorkSheetYn: 'Y',
    CustomerUse: 'Private',
    UseSpeakYn: 'Y',
  }
  return NextResponse.json({ ...student }, { status: 200 })
}
